### ISSUE TITLE
Permission denied: '/Library/Python/2.7/site-packages/pync/vendor'

### ISSUE THREAD

**Issue by greenmang0** [sindresorhus/weechat-notification-center#1]
I get following error when I load script.

I am running weechat latest version.

Weechat is installed through brew - `brew install weechat`
Pync is installed through pip - `sudo pip install pync`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pync/__init__.py", line 3, in <module>
    from TerminalNotifier import Notifier
  File "/Library/Python/2.7/site-packages/pync/TerminalNotifier.py", line 117, in <module>
    Notifier = TerminalNotifier()
  File "/Library/Python/2.7/site-packages/pync/TerminalNotifier.py", line 24, in __init__
    self.download_app()
  File "/Library/Python/2.7/site-packages/pync/TerminalNotifier.py", line 46, in download_app
    shutil.move(os.path.join(path_to_folder, "terminal-notifier.app"), self.app_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 295, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 174, in copytree
    os.makedirs(dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pync/vendor'`

**Comment by karbon62** [comment]
Hi

Please can someone help - I am also getting the same error:

Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/commands/install.py", line 299, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/req/req_install.py", line 813, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/req/req_install.py", line 1008, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/wheel.py", line 339, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/wheel.py", line 310, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/utils/__init__.py", line 70, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/selenium'

I've also tried: sudo chown -R $USER /Library/Python/2.7/site-packages/pync but don't think it has fixed it. I am now getting this: /Library/Python/2.7/site-packages/pync: No such file or directory

**Comment by thiagopnts** [comment]
Looks like you don't have `pync` installed, can you try:
`sudo pip install pync`

**Comment by karbon62** [comment]
Its fixed, thanks!

**Comment by rafaelcamargo** [comment]
Thanks from here too!

**Comment by HeidiW** [comment]
Thanks x3!!

**Comment by MissSharp** [comment]
@sindresorhus how can I restore from 'sudo chown -R $USER /Library/Python/2.7' ? thanks

**Comment by Avnikaur** [comment]
Hi!
Can any one help?

Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 326, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 746, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/IPython/__init__.py'

**Comment by thiagopnts** [comment]
@Avnikaur it seems to be a permissions error, can you try to run your command again with sudo?

**Comment by shreyamittal17** [comment]
OSError: [Errno 13] Permission denied: '/usr/Python2.7/os.py'

Can anyone help with this ? 

Thankyou in advance

**Comment by thiagopnts** [comment]
@shreyamittal17 you get this error when you run `pip install pync`?

**Comment by dblack** [comment]
In case it might still help anyone (sorry if it's just noise), I was having these permission problems a-go-go, until I ran `brew doctor` and it told me to consider deleting `~/.pydistutils.cfg`.

I considered.

I deleted.

All was well.

**Comment by pranaikumar** [comment]
File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/geopy'


The above error was obtained when I tried an installation. Came here through google. Tried using this after reading the above comments

sudo chown -R $USER /usr/local/lib/python2.7/dist-packages/geopy

Which gave me an error of no such file or directory. Can anyone help me out! Thankyou in advance.

**Comment by thiagopnts** [comment]
@pranaikumar have you tried to run your command with `sudo`?

**Comment by pranaikumar** [comment]
@thiagopnts  Yes I did use a sudo my exact command line was

sudo chown -R $USER /usr/local/lib/python2.7/dist-packages/geopy

**Comment by thiagopnts** [comment]
@pranaikumar I mean for the installation, which command did you run? Try running it with `sudo`

**Comment by pranaikumar** [comment]
@thiagopnts  I just used sudo and this is what I got as an error

Downloading/unpacking geopy==1.11.0 (from -r requirements.txt (line 1))
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement geopy==1.11.0 (from -r requirements.txt (line 1))

Iam actually installing it from my own computer.

**Comment by thiagopnts** [comment]
Looks like you're trying to install something else, not pync(which this thread is about). Your error now says it can't find the lib listed in the requirements.txt file

**Comment by pranaikumar** [comment]
@thiagopnts 
Yes Iam installing something else and stumbled upon a similar issue mentioned here hence I popped up my issue. Btw it's solved the geopy version mentioned in requirements.txt was wrong! Thanks for helping though.

**Comment by Natglobe** [comment]
I get this error when I type in the command: "chown: sudo: illegal user name"

**Comment by ellieandallen** [comment]
once i met the same problem,the code was pip install fuzzywuzzy,then i plus sudo in the front,it turns ok.

**Comment by dopexxx** [comment]
Dear all,

I tried the commands suggested above (`sudo chown -R $USER /Library/Python/2.7` and the same with the `site-package` folder). 
I still get this error:

`Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 293, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/easy_install.py' `

Could please somebody help me!?
Cheers!

**Comment by Newcool1230** [comment]
@thiagopnts 
how to fix
Traceback (most recent call last):
File "./setoolkit", line 34, in <module>
os.makedirs("/etc/setoolkit/")
File "/usr/lib/python2.7/os.py, line 157, in makedirs
mkdir(name,mode)

**Comment by thiagopnts** [comment]
guys this is only for `weechat-notification-center` related issues, for python support/help try stackoverflow.com
